ARROW-6148: [Packaging] Improve aarch64 support
Fetching Thrift fails without 'ca-certificates':

    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED]
    certificate verify failed: unable to get local issuer certificate
    (_ssl.c:1056)

And build fails without 'meson' installed:

    make[2]: Leaving directory '/build/apache-arrow-0.14.1/cpp_build'
    dh_auto_configure                               \
      --sourcedirectory=c_glib                      \
      --builddirectory=c_glib_build                 \
      --buildsystem=meson+ninja                     \
      --                                            \
      -Darrow_cpp_build_type=release                \
      -Darrow_cpp_build_dir=/build/apache-arrow-0.14.1/cpp_build    \
      -Dgtk_doc=true
            cd c_glib_build && LC_ALL=C.UTF-8 meson ../c_glib --wrap-mode=nodownload --buildtype=plain --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libdir=lib/aarch64-linux-gnu -Darrow_cpp_build_type=release -Darrow_cpp_build_dir=/build/apache-arrow-0.14.1/cpp_build -Dgtk_doc=true
    Can't exec "meson": No such file or directory at /usr/share/perl5/Debian/Debhelper/Dh_Lib.pm line 475.

Closes #5024 from hrw/master and squashes the following commits:

eddc53f9a <Sutou Kouhei> Remove Ubuntu cosmic
320612810 <Sutou Kouhei> Remove needless condition
c321dab17 <Sutou Kouhei> Remove needless option
b3ec88b66 <Sutou Kouhei> Align continuous line marks
2bc1644f9 <Sutou Kouhei> Update comment
db566d163 <Sutou Kouhei> Drop Ubuntu cosmic
01d709e3b <Sutou Kouhei> Drop Ubuntu cosmic
92f70ed6e <Sutou Kouhei> Fix version
67d9f2d2a <Sutou Kouhei> Copy qemu-aarch64-static to all docker context directories
dabcabe64 <Sutou Kouhei> Stop on failure
08f16a694 <Sutou Kouhei> Add missing qemu-dummy-static
35eef17cc <Sutou Kouhei> Use pattern instead of amd64/arm64/all
c949fcd72 <Sutou Kouhei> Share Dockerfile with amd64 and arm64
abc522f54 <Marcin Juszkiewicz> Sync Ubuntu 'xenial' packaging
a0c970990 <Marcin Juszkiewicz> deb: documentation packages should be 'all'
aeaffefd6 <Marcin Juszkiewicz> docker: handle installation of x86 only packages
25b11f8cb <Marcin Juszkiewicz> deb: enable Gandiva for more architectures
12d988130 <Marcin Juszkiewicz> deb: enable clang-7 for arm64
64a7d4a4f <Marcin Juszkiewicz> deb: use proper switch to enable Plasma

Lead-authored-by: Marcin Juszkiewicz <marcin.juszkiewicz@linaro.org>
Co-authored-by: Sutou Kouhei <kou@clear-code.com>
Signed-off-by: Sutou Kouhei <kou@clear-code.com>