[branch-50] Fix ambiguous column names in substrait conversion #17299 (#18077)
## Which issue does this PR close?

- Related to #18072 
- Related to #17294
- Backports https://github.com/apache/datafusion/pull/17299 to branch-50


## Rationale for this change

Fix ambiguous column names in substrait conversion as a result of
literals before and after a join being assigned the same name.

More information in the issue, but say you have a NULL literal before a
join called "column1" and then you create a new NULL column after the
join called column2, you would get an ambiguous column name errors like.

```
Error: SchemaError(AmbiguousReference { field: Column { relation: Some(Bare { table: "left" }), name: "UTF8(NULL)" } }, Some(""))
```


## What changes are included in this PR?

Simply alias all literals as they're converted to have a UUID name.

## Are these changes tested?

Yes.
Tested by using substrait-java with this query

```
./isthmus-cli/build/graal/isthmus --create "create table A (a int); create table B (a int, c int); create table C (a int, d int)" "select t.*, C.d, CAST(NULL AS VARCHAR) as e from (select a, CAST(NULL AS VARCHAR) as c from A UNION ALL select a, c from B) t LEFT JOIN C ON t.a = C.a"
```

## Are there any user-facing changes?

Co-authored-by: Xander <zander181@googlemail.com>
Co-authored-by: Xander Bailey <xbailey@palantir.com>
Co-authored-by: Andrew Lamb <andrew@nerdnetworks.org>