Fix metrics for repartition when `preserve_order=true` (#20924)
## Which issue does this PR close?
Found this when working on
https://github.com/apache/datafusion/pull/20875/
<!--
We generally require a GitHub issue to be filed for all bug fixes and
enhancements and this helps us generate change logs for our releases.
You can link an issue to this PR using the GitHub syntax. For example
`Closes #123` indicates that this PR will close issue #123.
-->

- Closes #.

## Rationale for this change
Metric reporting was previously incorrect for `RepartitionExec` if
preserve order was set to true.
<!--
Why are you proposing this change? If this is already explained clearly
in the issue then this section is not needed.
Explaining clearly why changes are proposed helps reviewers understand
your changes and offer better suggestions for fixes.
-->

## What changes are included in this PR?

<!--
There is no need to duplicate the description in the issue here but it
is sometimes worth providing a summary of the individual changes in this
PR.
-->
Create new metrics before creating `PerPartitionStream`
## Are these changes tested?
Yes and confirmed that this fails on main:
```
     thread 'repartition::test::test_preserve_order_output_rows_not_double_counted' (12487869)
      panicked at datafusion/physical-plan/src/repartition/mod.rs:3007:9:
     assertion `left == right` failed: metrics output_rows (8) should match actual rows
     collected (4), not double-count
       left: 8
      right: 4
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
<!--
We typically require tests for all PRs in order to:
1. Prevent the code from being accidentally broken by subsequent changes
2. Serve as another way to document the expected behavior of the code

If tests are not included in your PR, please explain why (for example,
are they covered by existing tests)?
-->

## Are there any user-facing changes?

<!--
If there are user-facing changes then we may require documentation to be
updated before approving the PR.
-->

<!--
If there are any breaking changes to public APIs, please add the `api
change` label.
-->