feat: remove extra Rows from ReusableRows
Fixes: #23801

It will only work after https://github.com/apache/datafusion/pull/23619
is merged, until then test_round_robin_tie_breaker_success will fail:

Error: Internal("Rows from RowCursorStream is still in use by consumer")
test sorts::sort_preserving_merge::tests::test_round_robin_tie_breaker_success ... FAILED

The failure is triggered by prev_cursors from SortPreservingMergeStream
keeping the previous Cursor alive for round robin tie breaking purposes.
The optimization from #23619 only keeps the last Row, so there's no
longer a need to keep two Rows cached in ReusableRows.