[branch-52] Update to use lz4_flex 0.12.1 and quinn-proto 0.11.14 (#21009)
## Which issue does this PR close?

- part of https://github.com/apache/datafusion/issues/20855

## Rationale for this change

`cargo audit` is failing on on branch-52 like this:

```
...
Crate:     lz4_flex
Version:   0.12.0
Warning:   yanked

error: 2 vulnerabilities found!
warning: 4 allowed warnings found
```

here is an example of that heppening on CI:
https://github.com/apache/datafusion/actions/runs/23209529148/job/67454157529?pr=21004



## What changes are included in this PR?


- Update lz4_flex 50 0.12.1 (non yanked)

## Are these changes tested?

<!--
We typically require tests for all PRs in order to:
1. Prevent the code from being accidentally broken by subsequent changes
2. Serve as another way to document the expected behavior of the code

If tests are not included in your PR, please explain why (for example,
are they covered by existing tests)?
-->

## Are there any user-facing changes?

<!--
If there are user-facing changes then we may require documentation to be
updated before approving the PR.
-->

<!--
If there are any breaking changes to public APIs, please add the `api
change` label.
-->