Fix data for tpch_csv and tpch_csv10 (#19034)
## Which issue does this PR close?

<!--
We generally require a GitHub issue to be filed for all bug fixes and
enhancements and this helps us generate change logs for our releases.
You can link an issue to this PR using the GitHub syntax. For example
`Closes #123` indicates that this PR will close issue #123.
-->

- Closes #.

## Rationale for this change

When I try to ensure the data is available for the tpch_csv benchmark, I
get an error:
```
$ ./benchmarks/bench.sh data tpch_csv
```

```
***************************
DataFusion Benchmark Runner and Data Generator
COMMAND: data
BENCHMARK: tpch_csv
DATA_DIR: /Users/andrewlamb/Software/datafusion2/benchmarks/data
CARGO_COMMAND: cargo run --release
PREFER_HASH_JOIN: true
***************************
Error: unknown benchmark 'tpch_csv' for data generation
```

## What changes are included in this PR?

Fix the runner script to correctly create the data

## Are these changes tested?

<!--
We typically require tests for all PRs in order to:
1. Prevent the code from being accidentally broken by subsequent changes
2. Serve as another way to document the expected behavior of the code

If tests are not included in your PR, please explain why (for example,
are they covered by existing tests)?
-->

## Are there any user-facing changes?

<!--
If there are user-facing changes then we may require documentation to be
updated before approving the PR.
-->

<!--
If there are any breaking changes to public APIs, please add the `api
change` label.
-->