ARROW-10034: [Rust] Fix Rust build on master
Reverts ARROW-9977 and fixes one other conflict.

I was seeing compilation errors like this:

```
error[E0599]: no method named `value` found for reference `&array::array::StringArray` in the current scope
  --> arrow/src/compute/kernels/aggregate.rs:39:35
   |
39 |                 let item = $array.value(i);
   |                                   ^^^^^ method not found in `&array::array::StringArray`
```

Closes #8213 from andygrove/fix-rust-build-sep17

Authored-by: Andy Grove <andygrove@nvidia.com>
Signed-off-by: Andy Grove <andygrove@nvidia.com>