feat: remove extra Rows from ReusableRows (#23802)
## Which issue does this PR close?

<!--
We generally require a GitHub issue to be filed for all bug fixes and
enhancements and this helps us generate change logs for our releases.
You can link an issue to this PR using the GitHub syntax. For example
`Closes #123` indicates that this PR will close issue #123.
-->

- Closes #23801

## Rationale for this change
This change reduces the peak allocated memory by removing the
unnecessary Rows from being cached.

It will only work after https://github.com/apache/datafusion/pull/23619
is merged, until then test_round_robin_tie_breaker_success will fail:

Error: Internal("Rows from RowCursorStream is still in use by consumer")
test
sorts::sort_preserving_merge::tests::test_round_robin_tie_breaker_success
... FAILED

The failure is triggered by prev_cursors from SortPreservingMergeStream
keeping the previous Cursor alive for round robin tie breaking purposes.
The optimization from #23619 only keeps the last Row, so there's no
longer a need to keep two Rows cached in ReusableRows.

## What changes are included in this PR?

<!--
There is no need to duplicate the description in the issue here but it
is sometimes worth providing a summary of the individual changes in this
PR.
-->

## Are these changes tested?
There's an existing test that currenly fails with this change and it
will pass once #23619 is merged

## Are there any user-facing changes?
No