chore: Unbreak doctest CI (#20218)
File was renamed and split into smaller files as part of #20183.

## Rationale for this change

CI is failing with:

```
   Doc-tests datafusion
error: couldn't read `datafusion/core/src/../../../docs/source/library-user-guide/upgrading.md`: No such file or directory (os error 2)
    --> datafusion/core/src/lib.rs:1182:1
     |
1182 | / doc_comment::doctest!(
1183 | |     "../../../docs/source/library-user-guide/upgrading.md",
1184 | |     library_user_guide_upgrading
1185 | | );
     | |_^
     |
     = note: this error originates in the macro `include_str` which comes from the expansion of the macro `doc_comment::doctest` (in Nightly builds, run with -Z macro-backtrace for more info)
```

<!--
Why are you proposing this change? If this is already explained clearly
in the issue then this section is not needed.
Explaining clearly why changes are proposed helps reviewers understand
your changes and offer better suggestions for fixes.
-->

## What changes are included in this PR?

<!--
There is no need to duplicate the description in the issue here but it
is sometimes worth providing a summary of the individual changes in this
PR.
-->