ARROW-6128: [C++] Suppress a class-memaccess warning
    src/arrow/util/hashing.h:313:11: error: 'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'struct arrow::internal::HashTable<arrow::internal::ScalarMemoTable<nonstd::sv_lite::basic_string_view<char>, arrow::internal::HashTable>::Payload>::Entry'; use assignment or value-initialization instead [-Werror=class-memaccess]
         memset(entries_, 0, capacity * sizeof(Entry));
         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/arrow/util/hashing.h:197:10: note: 'struct arrow::internal::HashTable<arrow::internal::ScalarMemoTable<nonstd::sv_lite::basic_string_view<char>, arrow::internal::HashTable>::Payload>::Entry' declared here
       struct Entry {
              ^~~~~

Closes #5001 from kou/cpp-add-missing-void-star-cast and squashes the following commits:

9ee6eb0f8 <Sutou Kouhei>  Suppress a class-memaccess warning

Authored-by: Sutou Kouhei <kou@clear-code.com>
Signed-off-by: François Saint-Jacques <fsaintjacques@gmail.com>