[Crossbow][Docs] Add note to remind users not to use SSH URLs with Crossbow queue
Until ARROW-3572 is resolved, and maybe Crossbow has some unit tests, this will prevent some toes from being shot off. 

If you do use the SSH URL, you get the following error:

```
_pygit2.GitError: authentication required but no callback set
```