fix: Avoid panicing when stats are not available for a file group split (#23277)
## Which issue does this PR close?

- Closes https://github.com/apache/datafusion/issues/23219.

## Rationale for this change

The query from the issue: 

```sql
SELECT   (((Cast(id AS BIGINT) % 1024) + 1024) % 1024) AS computed_bucket
FROM     profile
ORDER BY computed_bucket,
         Cast(id AS BIGINT) limit 10;
```

panics:

```
thread 'main' panicked at .../datafusion-datasource-54.0.0/src/statistics.rs:100:48:
index out of bounds: the len is 0 but the index is 0
```

The underlying issue is that the current code panics when files are
split by statistics and there are no statistics available for the column
where the sort order is defined in this case `computed_bucket`.

## What changes are included in this PR?

- Fix in `MinMaxStatistics` to check if there are stats available for a
given column
- Test

## Are these changes tested?

Yes

## Are there any user-facing changes?

No