refactor and add simple function to deserialize and serialize proto b… (#4892)
* refactor and add simple function to deserialize and serialize proto bytes without reading/writing to file

* Resolve syntax issues causing compilation errors and modified serialize_bytes to return a Result

* [review] Introduce DataFusionError on failure to encode and decode bytes

* Change error type from DataFusionError::Internal -> DataFusionError::Substrait

* cargo fmt fixes