Workaround for compilation error due to rkyv#434.
When datafusion is used in a workspace that enables the `rkyv-64`
feature in the `chrono` crate, this triggered a Rust compilation error:

```
error[E0277]: can't compare `Option<&std::string::String>` with `Option<&mut std::string::String>`.
```

The root cause of the error is incorrect type unification in the Rust
compiler, as explained in https://github.com/rkyv/rkyv/issues/434. The
workaround pushes the compiler in the right direction by converting the
mutable reference to an immutable one manually.

Signed-off-by: Leonid Ryzhyk <leonid@feldera.com>